[package]
name = "simple-raytracer"
version = "0.1.0"
edition = "2021"
authors = ["Yi Cao <me@ycao.top>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fastrand = "2.0.0"

[profile.release]
debug = true
